/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmperson1.apps.superdoughnuts.gui;

import hmperson1.apps.superdoughnuts.SuperDoughnuts;
import scala.Unit;
import scala.Function0;
import scala.Function1;
import scala.collection.immutable.HashMap;
import scala.collection.immutable.Map;

/**
 * Panel shown at the start.
 *
 * @author HMPerson1
 */
class StartPanel extends javax.swing.JPanel {

    /**
     * Called when start is pressed.
     */
    private final Function1<Map<String, String>, Unit> startCallback;

    /**
     * Called when exit is pressed.
     */
    private final Function0<Unit> exitCallback;

    /**
     * Creates and populates a new {@link StartPanel}.
     *
     * @param startCallback called when start is pressed
     * @param exitCallback called when exit is pressed
     */
    public StartPanel(Function1<Map<String, String>, Unit> startCallback, Function0<Unit> exitCallback) {
        initComponents();
        this.startCallback = startCallback;
        this.exitCallback = exitCallback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        final javax.swing.JButton startButton = new javax.swing.JButton();
        final javax.swing.JButton exitButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(183, 131));

        jLabel1.setText("Name:");

        jLabel2.setText("Difficulty:");

        nameTextField.setText("Caleb");

        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anorexic", "Chubby", "Fat", "Morbidly Obese" }));

        startButton.setText("Start");
        startButton.setToolTipText("Nathan is a good boy.");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.setToolTipText("WHY?!?!?1?!?");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(difficultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {difficultyComboBox, jLabel1, jLabel2, nameTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exitButton, startButton});

    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startCallback.apply(
                new HashMap<String, String>()
                .<String>updated(SuperDoughnuts.KEY_PLAYERNAME(), nameTextField.getText())
                .<String>updated(SuperDoughnuts.KEY_DIFFICLUTY(), Integer.toString(difficultyComboBox.getSelectedIndex())));
    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        exitCallback.apply();
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JComboBox difficultyComboBox = new javax.swing.JComboBox();
    private final javax.swing.JTextField nameTextField = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
